OPERACIONES CRUD de las interfaces ESTUDIOS, PACIENTES, PROCEDIMIENTO…
AlvaroCastro1/Consultorio pull request #3
Opened 2024-05-07 20:50 UTC by gamenrick

OPERACIONES CRUD de las interfaces ESTUDIOS, PACIENTES, PROCEDIMIENOS, SIGNOS, TRATAMIENTOS, VACUNAS. EN LA CARPETA DE VACUNAS VIENE EL ARCHIVO DE LA BASE DE DATOS CON UNA LIGERA MODIFICACION A CONSIDERAR

2024-05-07 21:29 UTC, DiegoGomezTagleG01 requested changes
Requiere cambios y correciones, ya existe la conexion a la base de datos, solo es llamarla, hay archivos que no deberian estar subidos(Vacunas) e intentar separar los scripts de javascript en archivos separados

2024-05-07 21:29 UTC, DiegoGomezTagleG01 commented on public_html/Estudios/eliminarEstudio.php
> +if ($conn->connect_error) {
Ya existe una conexion de base de datos en la carpeta include, solo se importa

2024-05-07 21:29 UTC, DiegoGomezTagleG01 commented on public_html/Estudios/insertarEstudios.php
> +$status = 200;
Ya existe conexion a la base de datos

2024-05-07 21:29 UTC, DiegoGomezTagleG01 commented on public_html/Estudios/modificarEstudio.php
> +$status = 200;
Ya existe conexion a la base de datos

2024-05-07 21:29 UTC, DiegoGomezTagleG01 commented on public_html/Estudios/mostrarEstudios.php
> +
Ya existe conexion a la base de datos

2024-05-07 21:29 UTC, DiegoGomezTagleG01 commented on public_html/Procedimiento/procedimiento.html
> +    <link rel="stylesheet" href="../CSS/barraNav.css">
No son las importaciones del servidor, no va a funcionar cuando se suba a producción

2024-05-07 21:29 UTC, DiegoGomezTagleG01 commented on public_html/Procedimiento/procedimiento.html
> -    <script>
No se borran, son para que lea la barra de navegacion

2024-05-07 21:29 UTC, DiegoGomezTagleG01 commented on public_html/Tratamiento/Tratamiento.html
> -    <script>
Este script no se borra, es para la barra de navegacion

2024-05-07 21:29 UTC, DiegoGomezTagleG01 commented on public_html/Tratamiento/Tratamiento.html
>      <script>
separar si los script de javascript son muy largos

2024-05-07 21:29 UTC, DiegoGomezTagleG01 commented on public_html/Vacunas/consultorioS.sql
> +
Quitar la base de datos de aqui

2024-05-08 01:22 UTC, AlvaroCastro1 commented
Al igual que todos, deberias de realizar commits pequeños y constantes para que en caso de un error, se pueda detectar mas facilmente :)

Tambien añade a la gente que este en el área como reviewers, asi sera mas facil que se pueda hacer el merge automatico

2024-05-08 01:22 UTC, AlvaroCastro1 commented
Ademas, creo que deberan considerar los nuevos cambios en las interfeaces :+1:

2024-05-08 01:27 UTC, AlvaroCastro1 requested changes
Creo que hace falta considerar los nuevos cambios de las vistas :cry:

2024-05-08 02:48 UTC, closed without merging